apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: sidecar-operator-controller-manager
    controller-tools.k8s.io: "1.0"
  name: webhook-server-service
  namespace: operator-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9876
  selector:
    control-plane: sidecar-operator-controller-manager
    controller-tools.k8s.io: "1.0"
